version: '3'
services:
  # PHP Service
  php:
    build:
      context: ./docker-config
      dockerfile: php
    container_name: laravel-app
    # this is the path to your laravel project
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - network

  # MySQL Service
  mysql:
    image: mysql:latest  # Updated to the latest MySQL version
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-db
    restart: unless-stopped
    tty: true
    ports:
      - "3316:3306"  # Map the container port 9906 to the host port 9906
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./storage/mysql:/var/lib/mysql/
      - ./docker-config/mysql.cnf:/etc/mysql/my.cnf
    networks:
      - network

volumes:
  mysql-data:

networks:
  network:
